import Foundation

struct BibleBook {
    let id: Int
    let name: String
    let chapters: Int
}

let importBooks: [BibleBook] = [
    BibleBook(id: 0, name: "", chapters: 0),
    BibleBook(id: 1, name: "Genesis", chapters: 50),
    BibleBook(id: 2, name: "Exodus", chapters: 40),
    BibleBook(id: 3, name: "Leviticus", chapters: 27),
    BibleBook(id: 4, name: "Numbers", chapters: 36),
    BibleBook(id: 5, name: "Deuteronomy", chapters: 34),
    BibleBook(id: 6, name: "Joshua", chapters: 24),
    BibleBook(id: 7, name: "Judges", chapters: 21),
    BibleBook(id: 8, name: "Ruth", chapters: 4),
    BibleBook(id: 9, name: "1 Samuel", chapters: 31),
    BibleBook(id: 10, name: "2 Samuel", chapters: 24),
    BibleBook(id: 11, name: "1 Kings", chapters: 22),
    BibleBook(id: 12, name: "2 Kings", chapters: 25),
    BibleBook(id: 13, name: "1 Chronicles", chapters: 29),
    BibleBook(id: 14, name: "2 Chronicles", chapters: 36),
    BibleBook(id: 15, name: "Ezra", chapters: 10),
    BibleBook(id: 16, name: "Nehemiah", chapters: 13),
    BibleBook(id: 17, name: "Esther", chapters: 10),
    BibleBook(id: 18, name: "Job", chapters: 42),
    BibleBook(id: 19, name: "Psalms", chapters: 150),
    BibleBook(id: 20, name: "Proverbs", chapters: 31),
    BibleBook(id: 21, name: "Ecclesiastes", chapters: 12),
    BibleBook(id: 22, name: "Song of Solomon", chapters: 8),
    BibleBook(id: 23, name: "Isaiah", chapters: 66),
    BibleBook(id: 24, name: "Jeremiah", chapters: 52),
    BibleBook(id: 25, name: "Lamentations", chapters: 5),
    BibleBook(id: 26, name: "Ezekiel", chapters: 48),
    BibleBook(id: 27, name: "Daniel", chapters: 12),
    BibleBook(id: 28, name: "Hosea", chapters: 14),
    BibleBook(id: 29, name: "Joel", chapters: 3),
    BibleBook(id: 30, name: "Amos", chapters: 9),
    BibleBook(id: 31, name: "Obadiah", chapters: 1),
    BibleBook(id: 32, name: "Jonah", chapters: 4),
    BibleBook(id: 33, name: "Micah", chapters: 7),
    BibleBook(id: 34, name: "Nahum", chapters: 3),
    BibleBook(id: 35, name: "Habakkuk", chapters: 3),
    BibleBook(id: 36, name: "Zephaniah", chapters: 3),
    BibleBook(id: 37, name: "Haggai", chapters: 2),
    BibleBook(id: 38, name: "Zechariah", chapters: 14),
    BibleBook(id: 39, name: "Malachi", chapters: 4),
    BibleBook(id: 40, name: "Matthew", chapters: 28),
    BibleBook(id: 41, name: "Mark", chapters: 16),
    BibleBook(id: 42, name: "Luke", chapters: 24),
    BibleBook(id: 43, name: "John", chapters: 21),
    BibleBook(id: 44, name: "Acts", chapters: 28),
    BibleBook(id: 45, name: "Romans", chapters: 16),
    BibleBook(id: 46, name: "1 Corinthians", chapters: 16),
    BibleBook(id: 47, name: "2 Corinthians", chapters: 13),
    BibleBook(id: 48, name: "Galatians", chapters: 6),
    BibleBook(id: 49, name: "Ephesians", chapters: 6),
    BibleBook(id: 50, name: "Philippians", chapters: 4),
    BibleBook(id: 51, name: "Colossians", chapters: 4),
    BibleBook(id: 52, name: "1 Thessalonians", chapters: 5),
    BibleBook(id: 53, name: "2 Thessalonians", chapters: 3),
    BibleBook(id: 54, name: "1 Timothy", chapters: 6),
    BibleBook(id: 55, name: "2 Timothy", chapters: 4),
    BibleBook(id: 56, name: "Titus", chapters: 3),
    BibleBook(id: 57, name: "Philemon", chapters: 1),
    BibleBook(id: 58, name: "Hebrews", chapters: 13),
    BibleBook(id: 59, name: "James", chapters: 5),
    BibleBook(id: 60, name: "1 Peter", chapters: 5),
    BibleBook(id: 61, name: "2 Peter", chapters: 3),
    BibleBook(id: 62, name: "1 John", chapters: 5),
    BibleBook(id: 63, name: "2 John", chapters: 1),
    BibleBook(id: 64, name: "3 John", chapters: 1),
    BibleBook(id: 65, name: "Jude", chapters: 1),
    BibleBook(id: 66, name: "Revelation", chapters: 22)
]
