#!/usr/bin/env python3
"""work_lists.py — the Work Note's lists, rendered from the book.

The open items, the rulings and the leads live in Archive_Suggestions.db and are
written into Work Note.md BETWEEN TWO MARKERS. Everything outside those markers is
Saba's own writing and is never touched.

KEEP DATA SACRED (his law, 2026-07-25):
  * the raw Sermons.db is never opened here, for reading or writing
  * the Work Note is backed up before a single byte is changed
  * only the block between the markers is replaced; if the markers are missing they
    are ADDED at the end, and nothing existing is moved or removed
  * --show prints and writes nothing at all

    ./work_lists.py            render into Work Note.md
    ./work_lists.py --show     print only, touch nothing
"""
import shutil, sqlite3, sys, time
from pathlib import Path

DB   = Path.home() / "Archive/Archive_Suggestions.db"
NOTE = Path("/Users/saba/Desktop/Saba Code/Work Note.md")
START, END = "<!-- LISTS:START — generated by work_lists.py, do not hand-edit -->", "<!-- LISTS:END -->"

OWNER = {"Saba": "\U0001f464 **Saba**", "Scribe": "Scribe", "either": "either"}


def render():
    c = sqlite3.connect(f"file:{DB}?mode=ro", uri=True)
    out = [START, "",
           f"## \U0001f4cb THE LISTS — from the book, {time.strftime('%Y-%m-%d %H:%M')}", ""]

    rows = c.execute("""select title, detail, owner, needs, area, opened_at from open_items
                        where status in ('open','doing','blocked') order by
                        coalesce(priority,5), case owner when 'Saba' then 0 else 1 end, area, id""").fetchall()

    # the two of us, side by side — his hand on the left, the machine's on the right
    his   = [(t, n, a) for t, d, o, n, a, _ in rows if o == "Saba"]
    mine  = [(t, n, a) for t, d, o, n, a, _ in rows if o != "Saba"]
    out += [f"### The two of us — {len(his)} his, {len(mine)} mine", "",
            "| \U0001f464 **SABA** — his eye, his ear, his word, his ask | ✦ **SCRIBE** — the machine's hand |",
            "|---|---|"]
    for i in range(max(len(his), len(mine))):
        l = f"**{his[i][0]}**<br><sub>waits on {his[i][1]} · {his[i][2]}</sub>" if i < len(his) else ""
        r = f"**{mine[i][0]}**<br><sub>waits on {mine[i][1]} · {mine[i][2]}</sub>" if i < len(mine) else ""
        out.append(f"| {l} | {r} |")
    out += ["", "*Nothing crosses the line by itself: the machine never does what is his,"
            " and he is never handed what the machine can do.*", ""]

    out.append(f"### Open — {len(rows)}")
    out.append("")
    out.append("| what | area | whose | waits on |")
    out.append("|---|---|---|---|")
    for t, d, o, n, a, _ in rows:
        out.append(f"| **{t}** — {d or ''} | {a or ''} | {OWNER.get(o, o)} | {n or ''} |")

    done = c.execute("select count(*) from open_items where status='done'").fetchone()[0]
    if done:
        out += ["", f"*{done} closed. `select * from open_items where status='done'` to read them.*"]

    out += ["", "### Standing rulings", ""]
    for r, sc, b, on in c.execute(
            "select ruling, scope, because, ruled_on from rulings where standing=1 order by ruled_on, id"):
        out.append(f"- **{r}** — *{sc}* · {on}")
        if b:
            out.append(f"  <br>{b}")

    out += ["", "### Leads — Saba asks, never Claude", "",
            "| what is missing | where it might be | who to ask |", "|---|---|---|"]
    for w, wh, a, n in c.execute(
            "select what, where_it_might_be, ask_who, note from leads where status='open' order by id"):
        out.append(f"| **{w}**<br><sub>{n or ''}</sub> | {wh or ''} | {a or ''} |")

    c.close()
    out += ["", END]
    return "\n".join(out)


if __name__ == "__main__":
    block = render()
    if "--show" in sys.argv:
        print(block)
        raise SystemExit

    text = NOTE.read_text()
    shutil.copy(NOTE, NOTE.with_name(f"Work Note.before_lists_{time.strftime('%Y%m%d_%H%M%S')}.md"))

    if START in text and END in text:
        head, rest = text.split(START, 1)
        _, tail = rest.split(END, 1)
        text = head + block + tail          # only the block is replaced
    else:
        text = text.rstrip() + "\n\n" + block + "\n"   # nothing existing is disturbed

    NOTE.write_text(text)
    print(f"lists rendered into {NOTE.name} — everything outside the markers untouched")
